a=int(input("Enter the First number:"))
b=int(input("Enter the Secound number:"))
c=int(input("Enter the Third number:"))
print(a,">",b,"is",a>b)
print(a,"<",b,"is",a<b)
print(c,"==",a,"is",c==a)
print(c,"!=",b,"is",c!=b)
print(a,">=",b,"is",a>=b)
print(b,"<=",a,"is",b<=a)
